### PR TITLE
Create obj directory to fix macOS Big Sur compile problems

### PR DESCRIPTION
**Pull request by vesavlad**

### CODE REVIEW

**Comment by felixguendling** [comment]
Cannot reproduce the problem on Mac OS Big Sur.

**Comment by vesavlad** [comment]
what compiler are you using? brew install clang or the one from xcode?
Problem was initially seen with the xcode clang that has version 12

**Comment by felixguendling** [comment]
I'm using Apple Clang.

```
$ clang++ --version
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Which target are you building? `res-example`?

**Comment by felixguendling** [comment]
Ah. You probably should switch to the Ninja Generator.

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
ninja res-example
```

But with your change it works with Make, too?

Within MOTIS we decided to only support Ninja (on all platforms) but if the only change needed is the line to create the directory, I would be okay with this.

**Comment by vesavlad** [comment]
nope I was using for sure Makefile generator and the problem it was it cannot create that dir for generating objects in it. 
I taught that this might have been a problem with the newest version but it seems that the problem might have something to do with permissions that the generator has.

**Comment by felixguendling** [comment]
Currently, the PR ist empty (no files changed). Do you still need support for Makefiles? We can merge this to support Makefiles. Otherwise, it already works with Ninja.

**Comment by vesavlad** [comment]
it seems that pullout automatically pulled changes on my fork, overriding my changes, will retest and redo them if necessary and comeback with an answer

**Pull request merged**
